# Generated by Django 4.2.4 on 2023-08-07 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('season', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('airdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happydaysapp.episodes')),
            ],
        ),
        migrations.CreateModel(
            name='Character_Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happydaysapp.characters')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happydaysapp.scenes')),
            ],
        ),
    ]
